/*global define:true*/

define(['jquery', 'postal', 'data', 'template', 'jqueryext'],
  function ($, bus, data, template) {

  var offerUI = (function (selector) {
    var _this = this;
    var $offers = $(selector);
    var $viewing = $offers.find('#viewing');

    var _clear = function () {
      $viewing.find('> span').remove();
    };

    var _load = function (categories) {
      var offers = data.offers.inCategories(categories);
      _render(offers);
    };

    var _render = function (offers) {
      offers.forEach(function (offer, i) {
        var tmpl = new template.Offer(offer);
        tmpl.appendTo($viewing);
      });
      setTimeout(function () {
        $viewing.find('span')
          .addClass('show');
      }, 10);
    };

    // expands an offer's details when it is clicked; no message is
    // published for this event
    $viewing.on('click', '.learnyou', function () {
      $viewing.find('> .offer')
        .removeClass('extended')
        .swapClass('show', 'obscured');
      $(this).closest('span')
        .swapClass('obscured', 'extended');
      return false;
    });

    $viewing.on('click', '.close', function () {
      $(this).closest('.offer')
        .removeClass('extended');
      $viewing.find('> span')
        .swapClass('obscured', 'show');
      return false;
    });

    return {
      clear: _clear,
      load: _load,
      render: _render
    };
  }('#offers'));

  // subscribes to a "categories.changed" message generated by the tag
  // cloud module which indicates that a new category has been selected;
  // offers are then refreshed based on the new category
  bus.channel('learnyou', 'categories.changed').subscribe(function (categories) {
    offerUI.clear();
    offerUI.load(categories);
  });

  // subscribes to a "search.offers" message generated by the search
  // module; loads offers that match search results
  bus.channel('learnyou', 'search.offers').subscribe(function (offers) {
    offerUI.clear();
    offerUI.render(offers);
  });

  return offerUI;
});