USE [master]
GO

/****** Object:  Database [GrokMob]    Script Date: 08/20/2011 11:40:28 ******/
CREATE DATABASE [GrokMob] ON  PRIMARY ( 
    NAME = N'GrokMob',
    FILENAME = N'F:\Databases\Microsoft SQL Server 2008\MSSQL10.MSSQLSERVER\MSSQL\DATA\GrokMob.mdf',
    SIZE = 3072KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024KB
    )
LOG ON (
    NAME = N'GrokMob_log',
    FILENAME = N'F:\Databases\Microsoft SQL Server 2008\MSSQL10.MSSQLSERVER\MSSQL\DATA\GrokMob_log.ldf',
    SIZE = 15360KB,
    MAXSIZE = 2048GB,
    FILEGROWTH = 10%
    )
GO

ALTER DATABASE [GrokMob] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    begin
        EXEC [GrokMob].[dbo].[sp_fulltext_database] @action = 'enable'
    end
GO

ALTER DATABASE [GrokMob] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GrokMob] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GrokMob] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GrokMob] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GrokMob] SET ARITHABORT OFF 
GO

ALTER DATABASE [GrokMob] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GrokMob] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GrokMob] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GrokMob] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GrokMob] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GrokMob] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GrokMob] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GrokMob] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GrokMob] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GrokMob] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GrokMob] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GrokMob] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GrokMob] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GrokMob] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GrokMob] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GrokMob] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GrokMob] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GrokMob] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GrokMob] SET  READ_WRITE 
GO

ALTER DATABASE [GrokMob] SET RECOVERY FULL 
GO

ALTER DATABASE [GrokMob] SET  MULTI_USER 
GO

ALTER DATABASE [GrokMob] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GrokMob] SET DB_CHAINING OFF 
GO