USE [master]
GO

/****** Object:  Database [GrokMobEventStore]    Script Date: 08/20/2011 11:39:49 ******/

CREATE DATABASE [GrokMobEventStore] ON  PRIMARY (
    NAME = N'GrokMobEventStore',
    FILENAME = N'F:\Databases\Microsoft SQL Server 2008\MSSQL10.MSSQLSERVER\MSSQL\DATA\GrokMobEventStore.mdf',
    SIZE = 3072KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024KB
    )
LOG ON (
    NAME = N'GrokMobEventStore_log',
    FILENAME = N'F:\Databases\Microsoft SQL Server 2008\MSSQL10.MSSQLSERVER\MSSQL\DATA\GrokMobEventStore_log.ldf',
    SIZE = 15360KB,
    MAXSIZE = 2048GB,
    FILEGROWTH = 10%
    )
GO

ALTER DATABASE [GrokMobEventStore] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    begin
        EXEC [GrokMobEventStore].[dbo].[sp_fulltext_database] @action = 'enable'
    end
GO

ALTER DATABASE [GrokMobEventStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GrokMobEventStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GrokMobEventStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GrokMobEventStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GrokMobEventStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GrokMobEventStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GrokMobEventStore] SET  READ_WRITE 
GO

ALTER DATABASE [GrokMobEventStore] SET RECOVERY FULL 
GO

ALTER DATABASE [GrokMobEventStore] SET  MULTI_USER 
GO

ALTER DATABASE [GrokMobEventStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GrokMobEventStore] SET DB_CHAINING OFF 
GO